// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {pdf} from '../models';
import {history} from '../models';
import {document} from '../models';
import {ocr} from '../models';
import {frontend} from '../models';

export function CheckProcessedPages(arg1:Array<number>):Promise<Record<string, any>>;

export function DeleteHistoryRecord(arg1:number):Promise<void>;

export function ExportProcessingResults(arg1:string):Promise<string>;

export function ExportText(arg1:Array<number>,arg2:string):Promise<string>;

export function ExtractNativeText(arg1:number):Promise<string>;

export function GetAppVersion():Promise<Record<string, string>>;

export function GetConfig():Promise<config.AppConfig>;

export function GetCurrentDocument():Promise<pdf.PDFDocument>;

export function GetDocumentHistoryPages(arg1:string):Promise<Array<history.HistoryPage>>;

export function GetDocumentInfo(arg1:string):Promise<document.DocumentInfo>;

export function GetHistoryPages(arg1:number):Promise<Array<history.HistoryPage>>;

export function GetHistoryRecords(arg1:number):Promise<Array<history.HistoryRecord>>;

export function GetPDFPath():Promise<string>;

export function GetPageImage(arg1:number):Promise<Array<number>>;

export function GetProcessingStats():Promise<Record<string, any>>;

export function GetSupportedFormats():Promise<Array<string>>;

export function GetSupportedModels():Promise<Array<ocr.ModelInfo>>;

export function Greet(arg1:string):Promise<string>;

export function LoadDocument(arg1:string):Promise<void>;

export function LoadPDF(arg1:string):Promise<void>;

export function ProcessPages(arg1:Array<number>):Promise<void>;

export function ProcessPagesForce(arg1:Array<number>):Promise<void>;

export function ProcessWithAI(arg1:Array<number>,arg2:string):Promise<void>;

export function SaveBinaryFileWithDialog(arg1:string,arg2:string,arg3:Array<frontend.FileFilter>):Promise<string>;

export function SaveFileWithDialog(arg1:string,arg2:string,arg3:Array<frontend.FileFilter>):Promise<string>;

export function SearchHistory(arg1:string,arg2:number):Promise<Array<history.SearchResult>>;

export function SelectFile():Promise<string>;

export function TestAIConnection():Promise<void>;

export function UpdateConfig(arg1:config.AppConfig):Promise<void>;

export function UpdatePageText(arg1:number,arg2:string,arg3:string):Promise<void>;
