// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckProcessedPages(arg1) {
  return window['go']['main']['App']['CheckProcessedPages'](arg1);
}

export function CheckSystemDependencies() {
  return window['go']['main']['App']['CheckSystemDependencies']();
}

export function DeleteHistoryRecord(arg1) {
  return window['go']['main']['App']['DeleteHistoryRecord'](arg1);
}

export function ExportProcessingResults(arg1) {
  return window['go']['main']['App']['ExportProcessingResults'](arg1);
}

export function ExportText(arg1, arg2) {
  return window['go']['main']['App']['ExportText'](arg1, arg2);
}

export function ExtractNativeText(arg1) {
  return window['go']['main']['App']['ExtractNativeText'](arg1);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetCurrentDocument() {
  return window['go']['main']['App']['GetCurrentDocument']();
}

export function GetDocumentHistoryPages(arg1) {
  return window['go']['main']['App']['GetDocumentHistoryPages'](arg1);
}

export function GetDocumentInfo(arg1) {
  return window['go']['main']['App']['GetDocumentInfo'](arg1);
}

export function GetHistoryPages(arg1) {
  return window['go']['main']['App']['GetHistoryPages'](arg1);
}

export function GetHistoryRecords(arg1) {
  return window['go']['main']['App']['GetHistoryRecords'](arg1);
}

export function GetInstallInstructions() {
  return window['go']['main']['App']['GetInstallInstructions']();
}

export function GetPDFPath() {
  return window['go']['main']['App']['GetPDFPath']();
}

export function GetPageImage(arg1) {
  return window['go']['main']['App']['GetPageImage'](arg1);
}

export function GetProcessingStats() {
  return window['go']['main']['App']['GetProcessingStats']();
}

export function GetSupportedFormats() {
  return window['go']['main']['App']['GetSupportedFormats']();
}

export function GetSupportedModels() {
  return window['go']['main']['App']['GetSupportedModels']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function LoadDocument(arg1) {
  return window['go']['main']['App']['LoadDocument'](arg1);
}

export function LoadPDF(arg1) {
  return window['go']['main']['App']['LoadPDF'](arg1);
}

export function ProcessPages(arg1) {
  return window['go']['main']['App']['ProcessPages'](arg1);
}

export function ProcessPagesForce(arg1) {
  return window['go']['main']['App']['ProcessPagesForce'](arg1);
}

export function ProcessWithAI(arg1, arg2) {
  return window['go']['main']['App']['ProcessWithAI'](arg1, arg2);
}

export function SaveBinaryFileWithDialog(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveBinaryFileWithDialog'](arg1, arg2, arg3);
}

export function SaveFileWithDialog(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveFileWithDialog'](arg1, arg2, arg3);
}

export function SearchHistory(arg1, arg2) {
  return window['go']['main']['App']['SearchHistory'](arg1, arg2);
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function TestAIConnection() {
  return window['go']['main']['App']['TestAIConnection']();
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}

export function UpdatePageText(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdatePageText'](arg1, arg2, arg3);
}
